DROP TABLE IF EXISTS "moderation_log";
--;;
DROP TABLE IF EXISTS "staff";
--;;
DROP TYPE IF EXISTS "enum_roles";
--;;
DROP TRIGGER IF EXISTS tie_media_to_post ON media;
--;;
DROP FUNCTION IF EXISTS tie_media_to_post_fnc();
--;;
DROP TABLE IF EXISTS "media" CASCADE;
--;;
DROP TABLE IF EXISTS "posts" CASCADE;
--;;
DROP TRIGGER IF EXISTS tie_primary_to_thread ON threads;
--;;
DROP FUNCTION IF EXISTS tie_primary_to_thread_fnc();
--;;
DROP TRIGGER IF EXISTS post_increment ON posts;
--;;
DROP FUNCTION IF EXISTS post_increment_fnc();
--;;
DROP TABLE IF EXISTS "threads" CASCADE;
--;;
DROP TABLE IF EXISTS "boards" CASCADE;
